openapi: 3.0.0
info:
  title: File API
  version: 1.0.0
paths:
  /writeFile:
    post:
      summary: Writes content to a file
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                filePath:
                  type: string
                  description: The path where the file should be written
                fileContent:
                  type: string
                  description: The content of the file
      responses:
        "200":
          description: File written successfully
        "500":
          description: Unable to write to file

  /readFile:
    get:
      summary: Reads content from a file
      parameters:
        - name: filePath
          in: query
          description: The path of the file to be read
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: File not found
        "500":
          description: Unable to read file
